# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

plugins:
  - rubocop-rails

require:
  - rubocop-capybara

AllCops:
  NewCops: enable

# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Style/StringLiterals:
  EnforcedStyle: single_quotes

inherit_from: .rubocop_todo.yml
