name: multipost-backend-development

services:
  mysql:
    image: mysql/mysql-server:latest
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
    ports:
      - 3306:3306

volumes:
  mysql-data:
